version: '3'
services:
  aquila01:
    image: mongo:4.4
    container_name: aquila01
    hostname: aquila01
    volumes:
      - ./mongod_aquila.conf:/etc/mongod.conf:ro
      - /mnt/mongodata/aquila01:/data/db:rw
    command: --config /etc/mongod.conf
    restart: always
